name: Deploy AlexIA Shared Resources
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
    paths:
      - iac/**
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy-shared-res:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy to shared env
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_SHARED_RG }}
        scope: 'resourcegroup'
        template: ./iac/shared.bicep
        failOnStdErr: false